import mongoose from "mongoose";

const postSchema = mongoose.Schema(
  {
    postedBy: {
      //we use this to store mongodb object id which gets auto generated by mongoDb
      type: mongoose.Schema.Types.ObjectId,
      ref: "User", //we get this from User model so we use this
      required: true,
    },
    text: {
      type: String,
      maxLenght: 500,
    },
    img: {
      type: String,
    },
    likes: {
      //array of user ids
      type: [mongoose.Schema.Types.ObjectId],
      ref: "User",
      default: [],
    },
    replies: [
      {
        userId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: true,
        },
        text: {
          type: String,
          required: true,
        },
        //to avoid getting another request just for profile and name we get these fields here
        userProfilePic: {
          type: String,
        },
        username: {
          type: String,
        },
      },
    ],
  },
  {
    timestamps: true,
  }
);

const Post = mongoose.model("Post", postSchema);

export default Post;
